#!/usr/bin/env python3
"""Compile rationale_index.md from per-file headers under 07_working/drafts/rationale/.

The index is a compiled navigation view, not a hand-maintained truth file
(see CURRENT-TRUTH Compiled Intake Rule). Markdown files contribute their
3-line-header line 1 (`# name | one-line purpose`); YAML files contribute
their `*_name:` key and a top-level `purpose:` line when present.

Usage:
  python3 tools/build_rationale_index.py            # rewrite the index in place
  python3 tools/build_rationale_index.py --check    # exit 1 if index is stale (advisory)

Exit: 0 = index written / up to date; 1 = --check found drift; 2 = usage error.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
RATIONALE_DIR = REPO / "07_working" / "drafts" / "rationale"
INDEX_NAME = "rationale_index.md"

PREAMBLE = """\
# rationale_index | one-line navigation index of 07_working/drafts/rationale/ contents
# related: [active_design_ledger, deferred_state_inventory, policy_filename_memo]
# phase: working_navigation

# Rationale Folder Index

> Status: compiled navigation aid; non-canonical; public-safe.
> Generated by `tools/build_rationale_index.py` from per-file headers. Do not hand-edit the table; fix the source file's header instead, then regenerate.
> Authority: none. This index does not promote any listed file; promotion still requires the documented governance path.

## Files in this folder

| File | One-line purpose |
|---|---|
"""

FOOTER = """\

## Out of scope

- Listing a file here does not promote it.
- This index does not replace `03_memory/registry/SHADOWMAS-FILE-STATUS-REGISTRY.v0.yaml`; the registry remains authoritative for tracked file status.
- Adding or removing a file here is documentation, not approval.
"""

MD_HEADER_RE = re.compile(r"^#\s*(?P<name>[^|]+?)\s*\|\s*(?P<purpose>.+?)\s*$")
YAML_NAME_RE = re.compile(r"^[a-z_]*name:\s*(?P<name>.+?)\s*$")
YAML_PURPOSE_RE = re.compile(r"^purpose:\s*(?P<purpose>.+?)\s*$")


def one_line_purpose(path: Path) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()[:25]
    if path.suffix == ".md":
        if lines:
            match = MD_HEADER_RE.match(lines[0])
            if match:
                return match.group("purpose").rstrip(".") + "."
        return "(no parseable line-1 header; add `# name | purpose`)"
    purpose = name = None
    for line in lines:
        if purpose is None:
            m = YAML_PURPOSE_RE.match(line)
            if m:
                purpose = m.group("purpose").strip("'\" >-")
        if name is None:
            m = YAML_NAME_RE.match(line)
            if m:
                name = m.group("name").strip("'\"")
    if purpose:
        return purpose.rstrip(".") + "."
    if name:
        return f"YAML artifact `{name}` (no top-level purpose line)."
    return "(no parseable name/purpose; add a `purpose:` line)"


def build_index() -> str:
    rows = []
    for path in sorted(RATIONALE_DIR.iterdir(), key=lambda p: p.name):
        if path.name == INDEX_NAME or path.is_dir():
            continue
        if path.suffix not in {".md", ".yaml", ".yml"}:
            continue
        rows.append(f"| `{path.name}` | {one_line_purpose(path)} |")
    rows.append(f"| `{INDEX_NAME}` | This file (compiled). |")
    return PREAMBLE + "\n".join(rows) + "\n" + FOOTER


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Compile the rationale folder index from file headers.")
    parser.add_argument("--check", action="store_true", help="advisory: exit 1 if index is stale")
    args = parser.parse_args(argv)

    if not RATIONALE_DIR.is_dir():
        print(f"ERROR: missing directory {RATIONALE_DIR}", file=sys.stderr)
        return 2

    expected = build_index()
    index_path = RATIONALE_DIR / INDEX_NAME
    current = index_path.read_text(encoding="utf-8") if index_path.exists() else ""

    if args.check:
        if current == expected:
            print("OK rationale_index.md is up to date")
            return 0
        print("FINDING rationale_index.md is stale; run tools/build_rationale_index.py (advisory)")
        return 1

    index_path.write_text(expected, encoding="utf-8")
    print(f"wrote {index_path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
