#!/usr/bin/env python3
"""Compile a one-screen DO-NOT-REDO surface for zero-memory and small-model agents.

The output lists what is already decided, rejected, or deferred-with-trigger,
so an agent does not re-propose or re-build it. It is a compiled view, not
truth (see CURRENT-TRUTH Compiled Intake Rule): every line is extracted from
its owning source file, and the source file always wins.

Sources compiled:
- 07_working/drafts/rationale/DECISION-*.md          (line-1 header purpose)
- 07_working/drafts/rationale/deferred_state_inventory.md
                                                     (section title + unlock trigger)
- 07_working/drafts/SHADOWMAS-LESSONS-QUEUE.v0.yaml  (lesson id + summary)

Usage:
  python3 tools/build_rework_guard.py            # rewrite the surface in place
  python3 tools/build_rework_guard.py --check    # exit 1 if stale (advisory)

Exit: 0 = written / up to date; 1 = --check found drift; 2 = setup error.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
RATIONALE_DIR = REPO / "07_working" / "drafts" / "rationale"
DEFERRED = RATIONALE_DIR / "deferred_state_inventory.md"
LESSONS = REPO / "07_working" / "drafts" / "SHADOWMAS-LESSONS-QUEUE.v0.yaml"
OUTPUT = REPO / "00_entry" / "DO-NOT-REDO.compiled.v0.en.md"

PREAMBLE = """\
# DO-NOT-REDO.compiled.v0.en | compiled one-screen list of already-decided, rejected, and deferred items
# related: [deferred_state_inventory, rationale_index, SHADOWMAS-LESSONS-QUEUE]
# phase: compiled_entry_surface

> COMPILED ARTIFACT — generated by `tools/build_rework_guard.py`. Do not hand-edit;
> fix the owning source file, then regenerate. Sources always win over this view.
> Authority: none. This file prevents rework; it does not approve or reject anything new.

# Do Not Redo

Before proposing to build, remove, adopt, or re-design anything in this repo:

1. scan the three lists below;
2. if your idea matches a line, read the owning source file first;
3. to check broader prior art, run `tools/find_shadow_concept.sh '<keyword>'`.

A match does not mean "forbidden forever" — it means the decision record and its
reopen/unlock conditions already exist. Re-open through those conditions, not by
re-proposing from scratch.
"""

FOOTER = """\

## Where to look deeper

- full rationale folder index: `07_working/drafts/rationale/rationale_index.md`
- deferral details and triggers: `07_working/drafts/rationale/deferred_state_inventory.md`
- one-command prior-art search: `tools/find_shadow_concept.sh '<pattern>'`
"""

MD_HEADER_RE = re.compile(r"^#\s*(?P<name>[^|]+?)\s*\|\s*(?P<purpose>.+?)\s*$")
SECTION_RE = re.compile(r"^##+ (?!Purpose|Discipline|Reconsideration|Out of scope|Other deferred)(?P<title>.+)$")
TRIGGER_RE = re.compile(r"^- unlock trigger:\s*(?P<trigger>.*)$")


def decided_lines() -> list[str]:
    lines = []
    for path in sorted(RATIONALE_DIR.glob("DECISION-*.md")):
        first = path.read_text(encoding="utf-8").splitlines()[0]
        match = MD_HEADER_RE.match(first)
        purpose = match.group("purpose") if match else "(unparseable header)"
        lines.append(f"- {purpose} — `{path.relative_to(REPO)}`")
    return lines


def deferred_lines() -> list[str]:
    lines = []
    text_lines = DEFERRED.read_text(encoding="utf-8").splitlines()
    title = None
    for i, line in enumerate(text_lines):
        section = SECTION_RE.match(line)
        if section:
            title = section.group("title").strip()
            continue
        trigger = TRIGGER_RE.match(line.strip()) if title else None
        if trigger and title:
            parts = [trigger.group("trigger").strip()]
            for cont in text_lines[i + 1:]:
                stripped = cont.strip()
                if not stripped or stripped.startswith("- ") or stripped.startswith("#"):
                    break
                parts.append(stripped)
            lines.append(f"- **{title}** — unlock: {' '.join(parts)}")
            title = None
    return lines


def lesson_lines() -> list[str]:
    data = yaml.safe_load(LESSONS.read_text(encoding="utf-8"))
    lines = []
    for entry in data.get("entries") or []:
        lesson_id = entry.get("lesson_id", "?")
        summary = entry.get("short_summary", "(no summary)")
        status = (entry.get("human_decision") or {}).get("status", "?")
        lines.append(f"- `{lesson_id}` ({status}): {summary}")
    return lines


def build() -> str:
    sections = [PREAMBLE]
    sections.append("\n## Already decided (do not re-litigate without reopen conditions)\n\n"
                    + ("\n".join(decided_lines()) or "- (none recorded)") + "\n")
    sections.append("\n## Deferred with explicit unlock triggers (do not build early)\n\n"
                    + ("\n".join(deferred_lines()) or "- (none recorded)") + "\n")
    sections.append("\n## Recorded lessons (do not repeat these failures)\n\n"
                    + ("\n".join(lesson_lines()) or "- (none recorded)") + "\n")
    sections.append(FOOTER)
    return "".join(sections)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Compile the DO-NOT-REDO entry surface.")
    parser.add_argument("--check", action="store_true", help="advisory: exit 1 if stale")
    args = parser.parse_args(argv)

    for required in (RATIONALE_DIR, DEFERRED, LESSONS):
        if not required.exists():
            print(f"ERROR: missing source {required}", file=sys.stderr)
            return 2

    expected = build()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""

    if args.check:
        if current == expected:
            print("OK DO-NOT-REDO surface is up to date")
            return 0
        print("FINDING DO-NOT-REDO surface is stale; run tools/build_rework_guard.py (advisory)")
        return 1

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
